from yacs import CfgNode

DEFAULT = CfgNode()

DEFAULT.AGENT = CfgNode()
DEFAULT.AGENT.CENTRAL.GAMMA = 1.
DEFAULT.AGENT.CENTRAL = CfgNode()
DEFAULT.AGENT.CENTRAL.NAME = 'DQNCentral'
DEFAULT.AGENT.MEMORY = CfgNode()
DEFAULT.AGENT.MEMORY.NAME = 'Sequential Memory'
DEFAULT.AGENT.MEMORY.SIZE = 1
DEFAULT.AGENT.MEMORY.STACK = 1

DEFAULT.DEVICE = 'cuda'

DEFAULT.ENVIRONMENT = CfgNode()
DEFAULT.ENVIRONMENT.NAME = 'CartPole-v1'
DEFAULT.ENVIRONMENT.TEST_NUM = 1
DEFAULT.ENVIRONMENT.TRAIN_NUM = 1

DEFAULT.MAX_EPOCH = 1

DEFAULT.OUTPUT_DIR = 'runs'
DEFAULT.SEED = -1
DEFAULT.STEP_PER_EPOCH = 1
DEFAULT.VERSION = 2
