from yacs.config import CfgNode

DEFAULT = CfgNode()

DEFAULT.AGENT = CfgNode()
DEFAULT.AGENT.NAME = 'OffPolicyAgent'

DEFAULT.AGENT.CENTRAL = CfgNode()
DEFAULT.AGENT.CENTRAL.DEVICE = 'cpu'
DEFAULT.AGENT.CENTRAL.NAME = 'DQNCentral'
DEFAULT.AGENT.CENTRAL.TARGET_UPDATE_FREQUENCY = 0.005

DEFAULT.AGENT.MEMORY = CfgNode()
DEFAULT.AGENT.MEMORY.NAME = 'LinkedMemory'
DEFAULT.AGENT.MEMORY.SIZE = 1

DEFAULT.AGENT.LIMBS = CfgNode()
DEFAULT.AGENT.LIMBS.NAME = 'OffPolicyLimbs'
DEFAULT.AGENT.LIMBS.PREPROCESS = None
DEFAULT.AGENT.LIMBS.POSTPROCESS = None

# Training process parameters
DEFAULT.AGENT.SOLUTION = CfgNode()
DEFAULT.AGENT.SOLUTION.BATCH_SIZE = 128
DEFAULT.AGENT.SOLUTION.GAMMA = 1.
DEFAULT.AGENT.SOLUTION.INIT_STEP = 0
DEFAULT.AGENT.SOLUTION.MAX_EPOCH = 1
DEFAULT.AGENT.SOLUTION.RETURN_STEP = 1
DEFAULT.AGENT.SOLUTION.STEP_PER_INTERACT = 1
DEFAULT.AGENT.SOLUTION.STEP_PER_EPOCH = 1
DEFAULT.AGENT.SOLUTION.TEST_NUM_EPISODE = 1
DEFAULT.AGENT.SOLUTION.UPDATE_PER_STEP = 1.

DEFAULT.ENVIRONMENT = CfgNode()
DEFAULT.ENVIRONMENT.NAME = 'CartPole-v1'
DEFAULT.ENVIRONMENT.TEST_NUM = 1
DEFAULT.ENVIRONMENT.TRAIN_NUM = 1

DEFAULT.OUTPUT_DIR = 'runs'
DEFAULT.SAVE = False
DEFAULT.SEED = -1

DEFAULT.VERSION = 2
